### ISSUE TITLE
More Namecheap alternatives that don't use bitpay also have LN support

### ISSUE THREAD

**Issue by bitmaster177** [alexk111/DeBitpay-Directory#1]
https://www.host4crypto.com/
https://www.lavavps.lt/

**Comment by alexk111** [comment]
Thanks for the links! Added as alternatives to Namecheap and Gandi.

**Comment by jayesh123804** [comment]
I never used their services and plans of Namecheap.

Yes, there are several Namecheap alternatives available that don't use bitpay also have LN support in the market.

I am currently using **DomainRacer** web hosting services from the last 2 years. **DomainRacer** is the most affordable alternatives to Namecheap. _DomainRacer_ is a global hosting company and they provide the best plans at a low cost.

**Learn More** : http://www.greentseo.com/best-namecheap-alternatives/

**Thank You...!!**
