### ISSUE TITLE
PeerName.com

### ISSUE THREAD

**Issue by peername** [alexk111/DeBitpay-Directory#14]
Please supply the following information:

* Places on DeBitpay.directory the alternative should be added to: domain names
* Name of the alternative: PeerName.com
* Registrar of blockchain-based (decentralized) domain names: .BIT, .COIN, .LIB, .ETH, .BAZAR, .ONION, .NEO ...
* URL of the alternative: https://peername.com/
* _Optional_: Twitter handle of the alternative: @peernamecom

**Comment by alexk111** [comment]
🙏 Added - pushed
