### ISSUE TITLE
Zak Servers | Reliable Offshore Dedicated Servers

### ISSUE THREAD

**Issue by zakservers** [alexk111/DeBitpay-Directory#17]
* Zak Servers
* Zak Servers offer reliable offshore dedicated servers, VPN, SSL Certificates & Domain Names, you can easily pay via bitcoin without the need of bitpay.
* https://www.zakservers.com
* https://twitter.com/zakservers
* https://blog.zakservers.com

**Comment by alexk111** [comment]
🙏 Added - pushed
