### ISSUE TITLE
A few more alternatives

### ISSUE THREAD

**Issue by pavlenex** [alexk111/DeBitpay-Directory#2]
Great idea. Here are some alternatives to the things you've listed. This mostly comes from [BTCPay's Directory,](https://directory.btcpayserver.org/) since those are merchants I am familiar with.

You should probably add, `how to add a new listing via PR`, wasn't sure what's your preferred workflow, so I'm posting the issue. These are just some on top of my head that fit into your categories, btcpay's directory has many more.

## Gaming (Alternatives to Microsoft)
- [GroupStream](https://www.groupsteam.com)
- [JoltFun](https://joltfun.com/)

## VPN
- [TorGuard](https://torguard.net/)
- [iVPN](https://ivpn.net)

## Hosting
- [CryptoShoho](https://cryptoho.st/)

## Hardware Wallets Shops
- [Casa](https://store.casa/)

**Comment by alexk111** [comment]
Thanks for the alternatives. Published.

> You should probably add, how to add a new listing via PR

README was the next point on my to-do list :)

**Comment by alexk111** [comment]
Added Issue templates for new places and alternatives.

**Comment by pavlenex** [comment]
Nice, thank you.
