### ISSUE TITLE
namesilo.com

### ISSUE THREAD

**Issue by peername** [alexk111/DeBitpay-Directory#24]
Please supply the following information:

* Name of the place: Namesilo.com
* A text description of the place that will fit the following template: ```Find alternatives to namesilo.com without BitPay.``` 
* URL of the place: https://namesilo.com

We need a domain registrar that accepts Bitcoin without BitPay.

**Comment by alexk111** [comment]
It's already there. Check this link: https://debitpay.directory/gandi/
