### ISSUE TITLE
Simple Buy

### ISSUE THREAD

**Issue by VitaliiLesyk** [alexk111/DeBitpay-Directory#3]
Please supply the following information:

Find aleternatives to pay for movies, events & subscriptions with Bitcoin without BitPay.
Find aleternatives to find and book cheap flights with Bitcoin without BitPay.
Find aleternatives to buy Amazon & Delta gift cards with Bitcoin without BitPay.
Find aleternatives to pay for movies, events & subscriptions with Bitcoin without BitPay.
Find aleternatives to buy games & digital codes with Bitcoin without BitPay.
Find aleternatives to buy games, movies & apps with Bitcoin without BitPay.
Find aleternatives to shop games & electronics with Bitcoin without BitPay.
Find aleternatives  to top up your mobile phone with Bitcoin without BitPay.

link: https://simplebuy.io/en

**Comment by alexk111** [comment]
Added SimpleBuy. 🙏
Could not find gift cards for companies under the cheap flights category.
