### ISSUE TITLE
G2A is using Bitpay - groupsteam is gone

### ISSUE THREAD

**Issue by bitpaint** [alexk111/DeBitpay-Directory#36]
Hey, seems like G2A is using Bitpay.
![image](https://user-images.githubusercontent.com/67663265/136574502-94565f29-d608-4690-8f35-586118f7d2a8.png)
groupsteam.com is gone.

IMO, Joltfun is the most legit store. They only ask for e-mail, accept Lightning and instant deliver the key.

**Comment by alexk111** [comment]
> Hey, seems like G2A is using Bitpay.

Bitbay, not Bitpay ;)

> groupsteam.com is gone.
> IMO, Joltfun is the most legit store. They only ask for e-mail, accept Lightning and instant deliver the key.

Thanks for reporting this. Will remove the groupsteam. For Joltfun will add the note.
