### ISSUE TITLE
[ALTERNATIVE] https://njal.la/

### ISSUE THREAD

**Issue by kensonxa** [alexk111/DeBitpay-Directory#4]
Please supply the following information:

* Places on DeBitpay.directory the alternative should be added to
I dont know what "places" means. It is a domain hoster.

* Name of the alternative
Njalla

* A text description of the alternative
Finally, a privacy-aware domain service.
Njalla protects you from ferocious domain predators.

* URL of the alternative
https://njal.la/

* _Optional_: Twitter handle of the alternative
https://twitter.com/njal_la

**Comment by alexk111** [comment]
Published 🙏
