### ISSUE TITLE
[ALTERNATIVE] Coincards.com

### ISSUE THREAD

**Issue by astupidmoose** [alexk111/DeBitpay-Directory#6]
As one of BTCPay's first merchants, we also host a large selection of gift cards for merchants and are a good alternative to many services.

Alternative Name: Coincards
Altenative Description: 
URL: https://coincards.com
Twitter: @coincards

Sites we should be listed as an alternative to: 
Webhallen
The D Hotel
Playasia
Newegg 
Microsoft 
Lush 
Kinguin 
Flight Centre
Gamesplanet 
EOM Travel
BitPay Wallet
airBaltic 

I'd also suggest adding Gyft and eGifter as sites that use Bitpay, and our own service as an alternative to both.

**Comment by alexk111** [comment]
Published. Thanks! 🙏
