### ISSUE TITLE
[ALTERNATIVE] Oak Furniture House

### ISSUE THREAD

**Issue by dannmat** [alexk111/DeBitpay-Directory#7]
- None of the existing DeBitPay categories cover furniture, so this merchant would need a new category of its own.

- Oak Furniture House

- “Find alternatives to buy oak furniture for the home and garden in the UK with Bitcoin without BitPay.”

- https://www.oakfurniturehouse.co.uk 

- @O_F_House

**Comment by alexk111** [comment]
Need a known store accepting Bitcoin via Bitpay, to add the alternative.

**Comment by dannmat** [comment]
Will this work? [Fancy](https://fancy.com/)

**Comment by alexk111** [comment]
Fancy offers a wide choice of goods, whereas Oak Furniture House only has furniture.

**Comment by dannmat** [comment]
Fancy was taken from the BitPay directory and was the closest store to Oak Furniture House that is listed by BitPay

**Comment by alexk111** [comment]
That's not enough. There should be a high probability that you can find a similar product on the proposed alternative. Check https://debitpay.directory/fancy/ for an example of an alternative to Fancy.
