### ISSUE TITLE
[ALTERNATIVE] Spy Equipment UK

### ISSUE THREAD

**Issue by dannmat** [alexk111/DeBitpay-Directory#8]
- Again, none of the DeBitPay existing categories cover furniture, so this merchant would need a new category of its own.

- Spy Equipment UK

- “Find alternatives to buy electronic surveillance, spy gadgets and spy equipment in the UK with Bitcoin without BitPay.”

- https://www.spyequipmentuk.co.uk/

- @SpyEquipmentUK

**Comment by alexk111** [comment]
Need a known store accepting Bitcoin via Bitpay, to add the alternative.

**Comment by dannmat** [comment]
Will this work? [FastTech](https://www.fasttech.com)

**Comment by alexk111** [comment]
FastTech offers a much wider choice of gadgets and electronics.

**Comment by dannmat** [comment]
FastTech was taken from the BitPay directory and was the closest store to Spy Equipment UK that is listed by BitPay

**Comment by alexk111** [comment]
That's not enough. There should be a high probability that you can find a similar product on the proposed alternative.
