### ISSUE TITLE
[ALTERNATIVE] Island Computers

### ISSUE THREAD

**Issue by dannmat** [alexk111/DeBitpay-Directory#9]
- List on existing “NewEgg Alternatives” 

- Island Computers 

- “Online computer shop where you can buy computer and telecommunication products with Bitcoin.” 

- https://islandcomputers.com

**Comment by alexk111** [comment]
It doesn't look like a good alternative to NewEgg. Inconsistent design, broken "contact us", tons of irrelevant links at the footer.
